### ISSUE TITLE
"New builds are now live" notification email is broken

### ISSUE THREAD

**Issue by slowriot** [itchio/butler#103]
After uploading builds (sometimes a significant time after), I eventually get an email that looks like:
![](https://i.imgur.com/9EONoen.png)

I presume it isn't really meant to look this way.

I wasn't sure if I should report it here, or on the itch.io tracker, but since this is triggered by butler uploads I assumed here was best.  Let me know if you'd prefer me to repost it on the other tracker instead.

**Comment by leafo** [comment]
fixed now, thanks for the report!
