### ISSUE TITLE
"butler: command not found" on Linux

### ISSUE THREAD

**Issue by bryanwillis7** [itchio/butler#106]
Running on Ubuntu 16.04. Butler was installed with the Itch.io app. I can see my butler executable file in  /config/itch/bin  clicking on it does nothing, navigating to that folder in bash and attempting to run it does nothing. and the butler command always yields the not found message. Tried doing this:

    On Mac & Linux, edit your ~/.bashrc or equivalent to include a line like:

export PATH="$PATH:~/bin" 

and still, nothing. I can't think of anything else to do. :/ Help would be DEEPLY appreciated.

**Comment by fasterthanlime** [comment]
> navigating to that folder in bash and attempting to run it does nothing. and the butler command always yields the not found message.

On most Linux installs, the current directory is not part of the path. So if you're in the `~/.config/itch/bin` directory, you'll need to run:

```bash
./butler
```

The `export PATH="$PATH:~/bin"` advice is for when you download butler yourself and actually put it in `~/bin` :)

Note that `~/.bashrc` is only evaluted when you start a new shell, so just editing it from an existing shell won't do anything, you'll have to log out & back in again.

Hope this helps!

**Comment by bryanwillis7** [comment]
ah thank you. It helps a lot. ./butler works for me. Strange. I've never had to do that for other programs.

either way I'm glad it works. :)

**Comment by fasterthanlime** [comment]
> I've never had to do that for other programs.

Other programs are typically installed to `/usr/bin` or something else that's already in the default `$PATH` :)
