### ISSUE TITLE
"url.Error Post"

### ISSUE THREAD

**Issue by Ragzouken** [itchio/butler#108]
*url.Error Post https://itch.io/api/1/7B9DN2B3UcoFJSok3SUX15EUH71ygcW7xKYBr4d1/wharf/builds/34657/files/128265: EOF
C:/Go/src/runtime/asm_386.s:1629 (0x44f991)

Not sure what this means but I'm guessing either there's a bug or you need a better error message. Command was a butler push

**Comment by fasterthanlime** [comment]
Sounds like a network error. Can you reproduce it (does it happen every time) ?

Does it happen on other computers you have access to? In the same network/in a different network?

Can you ping itch.io ?

**Comment by fasterthanlime** [comment]
See https://groups.google.com/forum/m/#!topic/Golang-Nuts/HsaLNTMq3eI - this error seems to happen when the server in question messes up badly. I wouldn't introduce a custom error message for this since it's not a "usual" error

**Comment by Ragzouken** [comment]
It worked just fine on retry, so i guess its a network error as you
suggested
