### ISSUE TITLE
Butler install it too clever ^^

### ISSUE THREAD

**Issue by delahee** [itchio/butler#122]
Hi,

Butler is very nice, there is only one thing that bugs me a tiny bit.
When installing it doesn't ask for directory, hence default directory is a user one. 

Problem is I use external processes with isolated users for butler, and in these processse there is no access to user home directory sometime... ideally it would be cool If I could choose at install time to put the itch app in a less boxed location so that I can still used boxed process to perform deployment steps.

Feel free to close if it brings more problems than advantages.

**Comment by fasterthanlime** [comment]
I'm happy witch itch.io/app installing its dependencies to %APPDATA% - but nobody's saying you need to use the app's copy of butler for your own usage :)

Separate download/install instructions are available here: https://itch.io/docs/butler/installing.html - and although butler stores secrets in user directories by default, you can override that by passing `--identity path/to/identity/file` !

We've planned on adding an <https://itch.io/butler> page to have more visible download links (to stable versions, not just bleeding-edge)

**Comment by delahee** [comment]
Very fine for me, that's what i've done. I'll close for now ^^ Bises.
