### ISSUE TITLE
Feature Request: config file and init function

### ISSUE THREAD

**Issue by digitalfiz** [itchio/butler#130]
It would be awesome if we could do something like `butler init` and it ask questions like what username, game and channel then puts them in a butler.json file that can automatically be read when simply doing things like `butler push` or `butler status`.

Those things should probably be overridable too incase you wanna push a different channel for whatever reason.

**Comment by fasterthanlime** [comment]
I would really love for butler to remain config-less, to respect the principle of least surprise.

I think pushing the same thing often is largely covered by existing build systems :)
