### ISSUE TITLE
push: Eschew golang antipattern of separate `done` and `errs` channel

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/butler#137]
This would let us get rid of this abomination: https://github.com/itchio/butler/blob/62ce303f5f183c533eef9265e61a4c6fcf669cf9/cmd/push/push.go#L289-L296

I general, the whole `push.go` file is full of beginner golang mistakes, which, yep, that was me.

**Comment by 200sc** [comment]
I made this changeset, but I'm 1. not confident the change is being tested by `go test ./...` and 2. am not positive this is what you were meaning to refactor this to, but if you'd like to work with this (or more, if there's other places that this problem shows up you want to point out) I'd be happy to PR this. 

https://github.com/200sc/butler/commit/4c014fcd107455372b26ca8d1b3c13df92a19669

**Comment by fasterthanlime** [comment]
Hey thanks! I'm going to merge this and keep cleaning up a bit.
