### ISSUE TITLE
Feature request: upgrade from old "bleeding edge" to newer stable release

### ISSUE THREAD

**Issue by rainerdeyke** [itchio/butler#149]
I can upgrade butler from a stable release to "bleeding edge" by running 'butler upgrade --head', but there appears to be no way to go back from "bleeding edge" to a stable release, even if the latest stable release is actually newer than the installed version of butler.  Running 'butler upgrade' gives me the unhelpful error message "✓ Bleeding-edge, not upgrading unless told to.".

**Comment by fasterthanlime** [comment]
As of v12.3.0, you can switch from bleeding-edge to stable with `butler upgrade --stable` and from stable to bleeding-edge with `butler upgrade --head`.

Just `butler upgrade` will update from head to head or stable to stable.

Obviously, from your current bleeding-edge version you'll need to `butler upgrade --head` before using the new functionality :)
