### ISSUE TITLE
Feature request: Filter files by a custom mask

### ISSUE THREAD

**Issue by dmitry-t** [itchio/butler#150]
Currently during a push command execution, the file tree walking routine ignores some files (e.g. .git). The mask list is hardcoded (filtering.IgnoredMasks).
It would be good if the push command accepted extra masks through some optional parameter (e.g. filter).

**Comment by fasterthanlime** [comment]
Actually, that's already the case :)

You can use `--ignore` with `butler push`. I've just added `--dry-run` (will be deploying soon) so it's clearer:

![image](https://user-images.githubusercontent.com/7998310/40917204-b396c0be-6802-11e8-90af-70e4b4a2e95c.png)
