### ISSUE TITLE
push/createBothFiles should return after sending errors

### ISSUE THREAD

**Issue by 200sc** [itchio/butler#155]
In the `createBothFiles` function in cmd/push, if `client.CreateBuildFile` returns an error it will also return a nil result. This means that in [this chunk of code](https://github.com/itchio/butler/blob/master/cmd/push/create_files.go#L18), there is a race condition nil-pointer panic:

```go
res, err := client.CreateBuildFile(buildID, buildType, itchio.BuildFileSubTypeDefault, itchio.FileUploadTypeDeferredResumable)
if err != nil {
	errs <- errors.Wrap(err, "creating build file on server")
}
comm.Debugf("Created %s build file: %+v", buildType, res.File)
```

If the `createFile` goroutine sends its error and then is scheduled to keep going before the program exits, `res` will be nil and the `comm.Debugf` line will panic on accessing the nil pointer. 

The fix for this is simple, just return after sending an error in `createFile`. 

An argument could be that this doesn't need to be fixed because the program will exit anyway, but if this crash happens you don't get any information on why the `CreateBuildFile` call failed.

**Comment by fasterthanlime** [comment]
I think this bug might no longer be present in master?

**Comment by 200sc** [comment]
Looks like it!
