### ISSUE TITLE
Beeps? in this day and age?

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/butler#158]
Here's a test executable that, for me, on Windows 10:

  * beeps once in mintty (msys2 shell)
  * beeps twice in cmd.exe

The third beep is never heard - this is what butler uses as a prefix for tasks.

Attached is beeptest.exe, signed with our certificate. I'm curious how it behaves on Windows 7!

[beeptest.zip](https://github.com/itchio/butler/files/2112248/beeptest.zip)

**Comment by 200sc** [comment]
I don't hear any beeps on Windows 7 in cmd.exe or powershell.

**Comment by fasterthanlime** [comment]
Update: for the original reporter:

  * `beeptest.exe` beeps once
  * even `butler -V` is enough to make their computer beep
  * it's run from a .bat script

**Comment by fasterthanlime** [comment]
@200sc do you get a beep if you run `butler upgrade` ?

**Comment by 200sc** [comment]
No, it didn't beep for me

cmd output if it matters:

```
E:\Downloads\beeptest>butler upgrade
∙ Looking for head upgrades...
√ Current version: d0a6e399509910618ef07d07d18152af5d44ca4e (head)
√ Latest version : e58c6568e85b0da37fea9e9f79ff9dd4b2d6a83f (head)
:: Do you want to upgrade now? [y/N] y
∙ https://broth.itch.ovh/butler/windows-amd64-head/e58c6568e85b0da37fea9e9f79ff9
dd4b2d6a83f/.zip
Scanning 3 entries for a stage two marker...
√ Upgraded butler from d0a6e399509910618ef07d07d18152af5d44ca4e (head) to e58c65
68e85b0da37fea9e9f79ff9dd4b2d6a83f (head). Have a nice day!
```

**Comment by 200sc** [comment]
False alarm, I had some bars in my audio mixer turned to zero-- I do get the single "should beep" beep from the test program.

**Comment by fasterthanlime** [comment]
> (also, butler upgrade dropped off a .gz file in my GOBIN but didn't extract the exectuable from it, so it looked like butler was broken, but that's on head, so)

That sounds like what an older butler would've done - I've changed the upgrade mechanism at some point (it uses .zip now, as you can see from the output!).

@200sc so beeptest beeps once, and `butler upgrade` doesn't beep at all ?

**Comment by 200sc** [comment]
That's correct.
