### ISSUE TITLE
Download stable version without getting the app

### ISSUE THREAD

**Issue by crassSandwich** [itchio/butler#159]
If I want to use Butler with a continuous integration provider like Travis, my options [seem to be](https://itch.io/docs/butler/installing.html) downloading the "bleeding edge" version or, to get the stable version, downloading the entire Itch app. For local use the app is nice to have, but it's a lot of bloat for CI just to get a stable Butler. It would be great if we could directly download and install a stable version.

**Comment by fasterthanlime** [comment]
@crassSandwich it's not exactly official yet, so I haven't updated the docs, but you can use these to get the latest stable:

  * https://broth.itch.ovh/butler/windows-amd64/LATEST/.zip
  * https://broth.itch.ovh/butler/windows-386/LATEST/.zip
  * https://broth.itch.ovh/butler/linux-amd64/LATEST/.zip
  * https://broth.itch.ovh/butler/linux-386/LATEST/.zip
  * https://broth.itch.ovh/butler/darwin-amd64/LATEST/.zip
