### ISSUE TITLE
Docs could use build instructions (especially for linux)

### ISSUE THREAD

**Issue by dodgyville** [itchio/butler#163]
This is a great project. I'd love build insturctions in the docs or the README

**Comment by fasterthanlime** [comment]
Like most golang projects, it should be:

  * Cloned in `$GOPATH/src/github.com/itchio/butler` (see [gopath docs](https://golang.org/doc/code.html#GOPATH))
  * Compiled with `go get`
    * You can add `-v` for extra info, and `-x` for even more information

On Windows, you'll need a compiler toolchain installed, I'm personally using gcc, installed with http://www.msys2.org/ - I compile from the msys2 shell.
