### ISSUE TITLE
Missing prereqs

### ISSUE THREAD

**Issue by srodrigo** [itchio/butler#184]
I was trying to set `net-4.7.1` on the itch manifest and was getting `Unknown prerequisite listed: net-4.7`. After digging in the source code of butler, I found this URL https://broth.itch.ovh/itch-redists/info/LATEST/unpacked here https://github.com/itchio/butler/blob/544e1b8609f8dab386cc67cd06bf999e47029b28/cmd/validate/validate.go#L261

The JSON returned when querying that URL contains `net-4.5.2`, `net-4.6` and `net-4.6.2`, but not `net-4.7` or `net-4.7.1`.

Is this correct? Is there currently a way to set `net-4.7.1` on the manifest? In case if not, would it be possible to update the list to get it available?

**Comment by srodrigo** [comment]
Hi @fasterthanlime does anyone in the team have any idea about this?

Thanks.

**Comment by fasterthanlime** [comment]
@srodrigo I do! It's all on me, I just have to add it.

**Comment by srodrigo** [comment]
Haha cool @fasterthanlime that would be awesome :)

In case this helps, it might be worth reviewing the whole list of missing .NET frameworks. I checked a few of them (mainly 4.7 and its patches), but there might be others missing as well?

**Comment by fasterthanlime** [comment]
@srodrigo 4.7.1 was just added! (it took longer than usual because I hadn't added any redists in a while).

I see 4.7.2 is out, so I might add that - in fact, is 4.7.1 even needed if 4.7.2 is there?

Let me know which versions I should add and I'll do it, now that I have everything at arm's reach.

**Comment by srodrigo** [comment]
@fasterthanlime thank you for that :)

> I see 4.7.2 is out, so I might add that - in fact, is 4.7.1 even needed if 4.7.2 is there?
I'm unsure. I'm targeting 4.7.1, so I guess installing 4.7.2 my game should work? I'm pretty new to C# unfortunately.

I don't have any other specific versions in mind, my problem was with 4.7.1 really. If people haven't complained/missed any versions, maybe we are fine for now.

**Comment by fasterthanlime** [comment]
> If people haven't complained/missed any versions, maybe we are fine for now.

I'll take it! Let's wait for someone else to complain.

**Comment by Mailaender** [comment]
> I see 4.7.2 is out, so I might add that - in fact, is 4.7.1 even needed if 4.7.2 is there?

> Let me know which versions I should add and I'll do it, now that I have everything at arm's reach.

Please add .NET framework 4.7.2 https://github.com/itchio/itch/issues/2458
