### ISSUE TITLE
Fails to compile when cross-compiling

### ISSUE THREAD

**Issue by dos1** [itchio/butler#190]
```
dos@yoga:~/git/butler$ GOOS=linux GOARCH=arm go build
build github.com/itchio/butler: cannot load github.com/itchio/dmcunrar-go/dmcunrar: no Go source files
```

Seems like it fails with any non-native configuration.
I have no slightest clue about golang's build system, so no idea if it's butler's or dmcunrar's fault.

**Comment by dos1** [comment]
Nothing puts your brain to work as well as clicking "send". Of course, it's a non-Go binding which needs special measures when cross-compiling :P

**Comment by fasterthanlime** [comment]
CGO_ENABLED=1 should do the trick

I'm told @icculus (hope that's the right GitHub username) has successfully compiled butler for ARM, maybe there's some knowledge to share here?

**Comment by dos1** [comment]
CGO_ENABLED would work with proper C toolchain setup, right. However, in the end I've just launched armv7 docker container and built it there - seems to work :)
