### ISSUE TITLE
Add SFX capabilities to the Windows uploads

### ISSUE THREAD

**Issue by fabiopicchi** [itchio/butler#191]
The focus of the issue I am opening are users that don't have the itch app installed and are simply downloading a file from the website.

I guess Linux and macOS users might be used to downloading zipped files but Windows users are used to downloading .exe files that simply run or install something to their computers. That said, I currently upload an [SFX](https://en.wikipedia.org/wiki/Self-extracting_archive) file created just with free and open source tools such as [7zip](https://www.7-zip.org/), for compression and self-extracting module, and [Resource Hacker](http://www.angusj.com/resourcehacker/) to simply copy the icon in my game's executable to the SFX file.

This way of working unfortunatelly does not make use of a lot of wonderful features provided but `butler`. The diffing should be totally possible if `butler` handled the compression and SFX generation and I would like to make a small contribution and add this feature, if the community thinks it makes sense.

**Comment by fasterthanlime** [comment]
Hi,

I'd like to add automatic installer generation in the backend at some point, however:

  - There is an acceptable alternative for non-technical users right now: just use https://itch.io/app
  - It is not an easy contribution to make, as the backend itself is proprietary, and involves a lot of moving parts
  - There are other priorities at the moment

**Comment by fasterthanlime** [comment]
The initial issue requests diffing of SFX files, more or less, which I'm not willing to add at the moment, so, closing!
