### ISSUE TITLE
Unable to set a custom userversion on butler push

### ISSUE THREAD

**Issue by Glusk2** [itchio/butler#198]
I am using `butler` with `travis` in project [Glusk2/sprouts]( https://github.com/Glusk2/sprouts).

`TRAVIS_TAG` is an environemnt variable, set by the Travis CI. I've tried setting the `userversion`  to `TRAVIS_TAG` on `butler push` but it didn't work (I've tried two different ways - https://github.com/Glusk2/sprouts/issues/143).

I am using [this](https://github.com/Glusk2/sprouts/blob/26d1099fc6eb81d0cc96a30aa6f577740f1e21a6/deploy.sh) deployment script. The files get pushed successfully but using itchio's default versioning (incrementing integers, starting from 0).

What am I doing wrong? Why can't I set the `userversion` to a specified value manually?

---

Sample build log with `butler` deployment:
https://travis-ci.com/Glusk2/sprouts/builds/130578088

**Comment by fasterthanlime** [comment]
The function `prepare_and_push` in `deploy.sh` only relays 3 arguments, so `--userversion` never gets passed to butler.
