### ISSUE TITLE
Android APK being zipped

### ISSUE THREAD

**Issue by lunarcloud** [itchio/butler#199]
This is bad as phone users often can't unzip things - expect to download APKs directly.

Using command:
`butler -v push export/android/name-of-game.apk "samsarette/name-of-game:android"`

This happened after upgrading butler recently

**Comment by fasterthanlime** [comment]
Hey there, you're absolutely right.

This isn't due to a butler upgrade, but to a bug I unwittingly introduced in its backend (while fixing another). I'm taking a look now.

**Comment by fasterthanlime** [comment]
A fix has been deployed.

**Comment by ricardocostaza** [comment]
> A fix has been deployed.

I think we have a regression. Push a APK file result in a ZIP.
