### ISSUE TITLE
Can't download butler

### ISSUE THREAD

**Issue by andreas-jonsson** [itchio/butler#202]
The links in the [documentation](https://itch.io/docs/butler/installing.html) seems to be wrong. Or is the server down?

[https://broth.itch.ovh/butler](https://broth.itch.ovh/butler)
[https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default](https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default)

I'm getting `itch.io API error (403): /games/239683/uploads: invalid key`

**Comment by fasterthanlime** [comment]
Good catch! Something did break indeed, it's all back up now.
