### ISSUE TITLE
"Too many files in zip"

### ISSUE THREAD

**Issue by icculus** [itchio/butler#216]
I'm a little vague on the details, as this was reported to me second-hand in August, but one our engine's users tried to upload a game with a large number of files in it, and was given this error:

 "There was a problem loading your project: Too many files in zip (5411 > 500)"

500 seems low--especially since the butler docs suggest it wastes less resources to upload loose files than a monolithic binary blob--and somewhat arbitrary.

Can that number get raised dramatically, or the limitation removed outright?

I can attempt to reproduce it here if more information or a test case is needed, but I'm hoping the error message alone makes the issue clear.

Thanks!

**Comment by rcgordon** [comment]
User that reported this says it only applies to uploading HTML builds:

https://discordapp.com/channels/608064116111966245/608064116984250379/764184486115409990

**Comment by leafo** [comment]
We've since bumped the limit up to 1k individual files, but here's why we have these limits in the first place: https://itch.io/docs/creators/html5#zip-file-requirements

Open for discussion of course

**Comment by MaxBittker** [comment]
is there a way to specific a directory but ignore some subdirectories? like node_modules, .git

**Comment by MaxBittker** [comment]
(I was uploading the wrong directory anyway, nvm)

**Comment by leafo** [comment]
Closing this ticket since this error is unrelated to butler, and a restriction from the itchio website. You can read more about why we have restrictions here: https://itch.io/docs/creators/html5#zip-file-requirements
