### ISSUE TITLE
Needs better install instructions for Windows

### ISSUE THREAD

**Issue by jtara1** [itchio/butler#223]
https://github.com/itchio/butler/blob/master/docs/installing.md

also, why not create the build and release directly with a github release?

**Comment by leafo** [comment]
> also, why not create the build and release directly with a github release?

Our internal CI is GitLab, it builds and publishes using butler to itch.io, which is used to serve the latest version from the itch.io website. We don't want a separate deploy pipeline at this time

**Comment by jtara1** [comment]
>do you have any recommendations on the install instructions for Windows you'd like to see?

My main confusion came from 

>Better yet, you can install it using the itch app, so it stays up-to-date.

This sounded like the recommended way to install but it doesn't give me further instructions for installing the cli.

I feel like the titles of the sections "The human-friendly way" and "The automation-friendly way" could be reworded to be more clear and direct. Do most users download directly from itchio.io or from the broth cdn?

**Comment by leafo** [comment]
Most users likely download from broth as far as I know. The app will keep an updated copy of butler.exe in the application data folder though, and you're welcome to use that one if you want.

**Comment by jtara1** [comment]
Can remove "Better yet, you can install it using the itch app, so it stays up-to-date.", or update to specify where to look for the butler.exe?

**Comment by jojoharry16** [comment]
So where does one find butler.exe with the itch app?

**Comment by jtara1** [comment]
I'd read through https://itch.io/docs/butler/installing.html or download from https://itchio.itch.io/butler

I don't remember figuring out how to use butler.exe from the itch app download.

**Comment by jtara1** [comment]
I'm going to close this. I think it's a nit pick anyways.
