### ISSUE TITLE
How to create receipt.json.gz files?

### ISSUE THREAD

**Issue by fcolecumberri** [itchio/butler#229]
Sometime, some games connot be downloaded using the itch launcher (ether by bugs of because the developer upload it on non-supported servers, like MEGA), on this cases one would assume it's not that big of a deal since the games can be downloaded with browsers, but when added into the games directory as mentioned on https://github.com/itchio/itch/issues/2481 the process fails because no `receipt.json.gz` was found on the `.itch`directory. I assumed it could be created with butler, but no Idea how.

**Comment by leafo** [comment]
Sorry, but the app will never support third party hosts for a wide range of issues that they create for us. If you want your users to take advantage of our app then you will have to host your game on our infrastructure.

Thanks!
