### ISSUE TITLE
Saving API key fails on Windows (can't create destination directory).

### ISSUE THREAD

**Issue by Chaser324** [itchio/butler#24]
When running `butler.exe login`, authentication succeeds but the API key fails to save with error:

```
Could not save API key: open C:\Users\Chase\.config\itch\butler_creds: The system cannot find the path specified.
```

Manually creating the `.config\itch\` directory bypasses this error.

I think fixing this should be as simple as replacing the `path.Dir()` call to `filepath.Dir()` in [authenticate.go](https://github.com/itchio/butler/blob/0350d15ba1cc9c7cdfc7b823bcbb2202238e67cb/authenticate.go#L265). I think the former only works with `/` path separators whereas the later will work with the OS specific path separator.

**Comment by fasterthanlime** [comment]
@Chaser324 just out of curiosity, what's the output of `butler -V` ?

I'll try to reproduce on windows today

**Comment by Chaser324** [comment]
`head, built on Apr 14 2016 @ 05:15:57`
