### ISSUE TITLE
Can butler update project meta info? details, store links etc 

### ISSUE THREAD

**Issue by paxperscientiam** [itchio/butler#247]
Hello,

I've got `butler` working nicely, though I'm wondering if it's possible to alter other aspects of a project beyond the code itself. For instance, if `butler` could be used to update a project's description or store links, that would be cool.

ok thanks

**Comment by leafo** [comment]
At this time you can edit and create pages through the web interface. Sorry for the inconvenience but for security reasons we would like to minimize the scope of what butler can do to an account.

**Comment by paxperscientiam** [comment]
Nothing to apologize about -- security is important, so that's very thoughtful of you.
