### ISSUE TITLE
Make target username/game not case-sensitive.

### ISSUE THREAD

**Issue by Chaser324** [itchio/butler#26]
It might be nice for commands that take a username/game target parameter to not treat them as case-sensitive.

In other words, butler should accept both "username/gamename" and "UserName/GameName".

**Comment by Deozaan** [comment]
Ditto, but for channel as well!

Win-64 vs. win-64 results in separate channels/uploads.

**Comment by fasterthanlime** [comment]
> Ditto, but for channel as well!

Maybe butler should just lowercase everything (targets + channel name).
