### ISSUE TITLE
Optionally specify display name with push command.

### ISSUE THREAD

**Issue by Deozaan** [itchio/butler#28]
Since Itch.io game pages don't display the date files were updated, there's no easy way to communicate to (potential) customers which version of your file is available on the site. For this, I use the custom display name of a file to include the version number.

For example:

I have MyGame-Win64.zip is displayed at "MyGame v1.3 Win64" but I have to manually update this display name each time I upload new builds. It would be nice if we could use butler's push command to specify the new display name to use for the new upload. Something like:

`butler push MyFolder username/game:channel "My New Display Name"`

**Comment by fasterthanlime** [comment]
Setting display name via push is an interesting thought, but I don't think it should be used for versioning — https://github.com/itchio/itch.io/issues/398 is my preferred solution to that.

**Comment by Deozaan** [comment]
Having the game/download page display the wharf/butler upload version number works for me.

Thinking about it more, what I'd really like is something that probably belongs in a new feature request "Issue" -- linking an existing upload (before butler, wharf, or the itch.app existed) to a new butler channel. So I guess I'll go create an issue for it and then come back here and add a link to it.

**Comment by smashriot** [comment]
I also would like to be able to set the file display name via the push AND/OR display version numbers as suggested in #398

**Comment by onimitch** [comment]
We're just starting to use itch.io refinery and butler, and we too would find this feature incredibly useful. Currently we have to constantly update the display name manually, which is a big pain.

**Comment by fasterthanlime** [comment]
Closing, as https://github.com/itchio/itch.io/issues/398 has been implemented.
