### ISSUE TITLE
Detect Android platform in channel name

### ISSUE THREAD

**Issue by Deozaan** [itchio/butler#29]
The documentation says:

> The name of a channel has meaning:
> - If it contains win or windows, it'll be tagged as a Windows executable
> - If it contains linux, it'll be tagged as a Linux executable
> - If it contains osx, it'll be tagged as a Mac executable

It would be nice if it would automatically detect and tag the Android platform (this could also be done by file extension, since virtually all Android builds will be packaged as .apk files).

Aside: And maybe "mac" and "macintosh" should be used to detect the Mac platform, in addition to the "osx" keyword.

**Comment by fasterthanlime** [comment]
(This is really more of an https://github.com/itchio/itch.io issue)

**Comment by Deozaan** [comment]
Yeah, it probably is. But since I was dealing with butler and the docs for butler, I came here instead. Sorry.

Should I recreate this issue there?

**Comment by fasterthanlime** [comment]
> Should I recreate this issue there?

No need, it's a good reminder to have it here, in this case.

**Comment by anissen** [comment]
Tagging a build with `:android` does actually mark it as an Android file even though it is not written in the documentation.

**Comment by fasterthanlime** [comment]
> Tagging a build with :android does actually mark it as an Android file even though it is not written in the documentation.

True! I fixed the docs in https://github.com/itchio/butler/commit/ddcbdec2f3c699a4df806e395a4ba7f6201b9f3f
