### ISSUE TITLE
tar.gz not supported

### ISSUE THREAD

**Issue by mrhelmut** [itchio/butler#30]
Hello!

I tried to push a .tar.gz to a linux channel and it turned out it is not a supported zip format.

Additionnaly, it would be nice if "linux" channels were published as .tar.gz  (I'm not a linuxian, but I've always been told that the community prefers tarballs over regular zip -- let me know if I'm wrong, it's for my linux culture --).

(Otherwise, everything with zip works fine. I tried to push a zip, and then a folder to the same channel and it worked great.)

**Comment by fasterthanlime** [comment]
> Additionnaly, it would be nice if "linux" channels were published as .tar.gz (I'm not a linuxian, but I've always been told that the community prefers tarballs over regular zip -- let me know if I'm wrong, it's for my linux culture --).

You're right, and it seems like a reasonable addition for the near future :)

**Comment by fasterthanlime** [comment]
Broken down into two smaller issues: #47 and #48
