### ISSUE TITLE
Trailing \ / in directory path

### ISSUE THREAD

**Issue by mrhelmut** [itchio/butler#31]
Hi there,

This is very minor, but when there is a ```\``` or ```/``` at the end of a path (à la Windows), the path is not recognized and butler won't work.
I believe this is only a bad habit of Windows users... ^^

**Comment by fasterthanlime** [comment]
@mrhelmut using the latest head version, I'm not able to reproduce the bug:

<img width="587" alt="screen shot 2016-04-23 at 17 07 22" src="https://cloud.githubusercontent.com/assets/7998310/14762241/e549f34e-0975-11e6-9507-6a42a0b8cf1c.png">

Can you `butler upgrade --head` and see if it's still a problem?

**Comment by mrhelmut** [comment]
```
D:\Butler>butler.exe push "D:\Releases\NeuroVoider_current\Steam_Windows\" flyingoakgames/neurovoider:windows --userversion-file buildnumber.txt

butler.exe: error: required argument 'target' not provided, try --help
```

**Comment by fasterthanlime** [comment]
@mrhelmut that looks like expected behavior from cmd.exe. The backslash escapes the double-quote that follows, which means that what butler actually receives is:

  * `push`
  * `D:\Releases\NeuroVoider_current\Steam_Windows" flyingoakgames/neurovoider:windows --userversion-file buildnumber.txt`

**Comment by mrhelmut** [comment]
Ahah, I feel dumb. ^^ Closing this now.
