### ISSUE TITLE
When pushing, paths aren't rebased properly

### ISSUE THREAD

**Issue by elisee** [itchio/butler#5]
`butler push` doesn't resolve paths relative to the uploaded folder's root, resulting full paths being sent to `wharf`.

(Also \ and / normalization should probably happen)

**Comment by fasterthanlime** [comment]
> (Also \ and / normalization should probably happen)

Actually I think this was working fine? The only problem was in the printing output

But if they weren't normalized the diffy upload wouldn't have worked, right?

**Comment by elisee** [comment]
Yeah, mostly added it because the mix of slashes and backslashes pointed to potential issues down the road, we didn't encounter any.

**Comment by fasterthanlime** [comment]
This has been solved ever since `tlc.Walk`
