### ISSUE TITLE
Make Butler friendlier for Java deployments

### ISSUE THREAD

**Issue by MyRealityCoding** [itchio/butler#57]
Butler already has features like supporting multiple channels, game updating etc. What I noticed while pushing a Java based game was, that I could not quite decide which channel should I use, since Java itself is system independent (only the JVM has OS dependent implementations).

**Goal:** _pushing a Java build via Butler and automatically mark the game for multiple operating systems/architectures. (so that users see that the game is supported by all those operating systems)_

It would be nice if Butler would support at least one of the following features, which would ease the process of auto-deploying Java games:
* **multi-channel support** make it possible to push via multiple channels at once (e.g. `user/game:channel1:channel2:channel3`
* **independent channel support** when pushing web based games or Java games which are by nature system independent, it would be nice to push to an *independent* channel which basically support all operating systems.

What do you think?

**Comment by fasterthanlime** [comment]
So I misunderstood - you're pushing the same thing for all 3 platforms. You should just be naming your (single) channel "windows-linux-mac", single push problem solved :)

P.S: you can always change what a channel's platform(s) is/are from the 'Edit game' page once the first build is up.
