### ISSUE TITLE
'file not found' when pushing .zip on Windows

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/butler#62]
See attached zip
[SHRUBNAUTRetinaTest.zip](https://github.com/itchio/butler/files/315022/SHRUBNAUTRetinaTest.zip)

> C:\Users\amos>butler which
You're running butler v0.14.11, built on Jun  1 2016 @ 11:39:58, from the following path:
C:\Users\amos\AppData\Roaming\itch\bin\butler.exe

zip is a game-maker export, created with 7-zip.

**Comment by cpudreams** [comment]
I had the same problem when pushing a zip file made with the built in zip support in Windows 10. I worked around it as suggested by Amos by pushing the unzipped folder instead.

**Comment by fasterthanlime** [comment]
As suspected, the culprit was path separators: zip entry paths contained backslashes, butler was looking for forward-slashes.

What I *didn't* realize though, was that doing `filepath.Clean(filepath.ToSlash(x))` would convert it back to backslashes on Windows. `filepath.ToSlash(filepath.Clean(x))` appears to work as intended!

**Comment by fasterthanlime** [comment]
Just shipped v0.15.1, which solves that issue. Run `butler update` to upgrade it to the latest version.
