### ISSUE TITLE
Pushing in 2 terminals at the same time results in HTTP error

### ISSUE THREAD

**Issue by peperbol** [itchio/butler#73]
I tried pushing 2 versions of my game at the same time, each in their own terminal
http://i.imgur.com/u3qkGlD.png
The left terminal started first and resulted in HTTP 404
The right terminal started after that resulting in a HTTP 505
Whenever I retried uploading in that same terminal I got the same error code again. 
When I opened a new terminal after that, my push was succesfull.
I used Gitbash in Windows as terminal which is based on MINGW64

**Comment by peperbol** [comment]
Maybe it was a coinsidence. It seemed fixed at first when i tried one at the time, but i'm not certain anymore where the cause is.

**Comment by fasterthanlime** [comment]
this is unrelated, please see #71 - updating to butler 0.16.0 mitigates the issue, but until google fully resolves it, it's out of our hands (short of deploying a US proxy, which I'm planning to do)
