### ISSUE TITLE
Feature Request: --stable flag to update from head to latest stable.

### ISSUE THREAD

**Issue by Deozaan** [itchio/butler#74]
I had a very old version of butler installed and when I tried to update it, it refused to update because it was on the bleeding-edge "head" version. It told me I could force an update to the latest head version by passing in the `--head` flag.

Sometimes the bleeding edge is useful, but generally I prefer things to be safe and stable.  What I wished for at that time was a way to use a `--stable` flag to force it to update to the latest stable.

Can we get that added, please?

**Comment by fasterthanlime** [comment]
Finally did it, see #149
