### ISSUE TITLE
"Butler Status" is broken?

### ISSUE THREAD

**Issue by Deozaan** [itchio/butler#77]
I uploaded a new channel. It completed and Butler told me "it should be up in a bit" and that I could check it with butler status. So I typed `butler status` and it showed me the help on how to use it. So I typed `butler status user/project:channel` (using my real user, project, and channel names exactly as entered in my earlier `butler push` command) and I get an error:

> *errors.errorString itch.io API error: invalid game
> C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/status.go:17 (0x4138ae)
> C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/main.go:398 (0x41ae7f)
> C:/Go/src/runtime/proc.go:183 (0x44f88e)
> C:/Go/src/runtime/asm_386.s:1612 (0x479631)

This is using the latest stable butler `v0.20.0, built on Sep 14 2016 @ 09:07:38`

**Comment by fasterthanlime** [comment]
you shouldn't include the `:channel` part when calling butler status.

(Although it could be more helpful about that)>

**Comment by Deozaan** [comment]
Typing `butler status` without any target displays the help, which says the target should include the channel part. So that help info needs to be corrected.

**Comment by fasterthanlime** [comment]
butler 0.21.0 is out, with a fixed help message. Thanks for the feedback! 🌠
