### ISSUE TITLE
dns timeout

### ISSUE THREAD

**Issue by r0nk** [itchio/butler#79]
Hiya folks, I'm getting a timeout whenever I try to use butler. 

I come bearing errors:

`dial tcp: lookup itch.io on 8.8.8.8:53: dial udp 8.8.8.8:53: i/o timeout
/home/amos/builds/630f4286/1/itchio/butler/src/github.com/itchio/butler/status.go:17 (0x41e9cd)
/home/amos/builds/630f4286/1/itchio/butler/src/github.com/itchio/butler/main.go:391 (0x425ec8)
/usr/local/go/src/runtime/proc.go:183 (0x45a7f4)
/usr/local/go/src/runtime/asm_amd64.s:2086 (0x48a9f1)
`

But DNS works fine if I try;

` $ ping itch.io -c 3
PING itch.io (45.33.55.10) 56(84) bytes of data.
64 bytes from li1005-10.members.linode.com (45.33.55.10): icmp_seq=1 ttl=52 time=31.1 ms
64 bytes from li1005-10.members.linode.com (45.33.55.10): icmp_seq=2 ttl=52 time=30.3 ms
64 bytes from li1005-10.members.linode.com (45.33.55.10): icmp_seq=3 ttl=52 time=32.3 ms

--- itch.io ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 4173ms
rtt min/avg/max/mdev = 30.353/31.273/32.344/0.819 ms`

As you can see, it's just slow, (this is somewhat normal given my internet provider (unfortunately)). The problem is butler times out too quickly, and it can't complete the DNS lookup. 

I'm digging around some of the source now to see if I can find the timeout declaration. Anyways I think I'd make more sense to have the timeout be at least 30 seconds or something, in order to support those of us on running on toasters.

**Comment by fasterthanlime** [comment]
What version of butler is this with?

**Comment by r0nk** [comment]
`$ butler version`
`head, built on Sep  9 2016 @ 13:13:56`

**Comment by fasterthanlime** [comment]
@r0nk can you try again with the latest butler head? I released a new one recently, and it's now built with go 1.7.1, which I know has dns fixes.

**Comment by r0nk** [comment]
I can confirm that the latest version works.

I modified a DNS server to make it sleep for 5 seconds before responding, and it created the error on the old build but not the newer one. Thus I'll close this issue.

For any internet adventurers out there with a similar problem,  you can configure something like dnsmasq in order to set up local caching, so you won't have to worry about DNS timeouts.

**Comment by fasterthanlime** [comment]
> I can confirm that the latest version works.

Awesome, thanks for testing! 🌟
