### ISSUE TITLE
Support puttygen public key format

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/butler#8]

**Comment by elisee** [comment]
Here's a dummy public key generated with puttygen:

    ---- BEGIN SSH2 PUBLIC KEY ----
    Comment: "rsa-key-20151216"
    AAAAB3NzaC1yc2EAAAABJQAAAQEA0n8jAbpnEk0bTdFu3kR0SoIKGz1mxKO3+REo
    masIZQExXltJchkVi5pX6XIp6pgdq2E5hXQYEg488X9ujoHNP/8YlsMaAh57Y9io
    53+U8Rjqz+SiqR2bqCKmwwLulP3oEZJSffrG1Cy1WI5swW/IZUPYXYJmOPiOIbUa
    nJvCXDhcnRuluZYL8FUGz2M3D1rnHP+ATC/5OMHqr8kyWKyaZZT3dJqJsa3SArVL
    x7OcebgivRegvGmnA0W1vakkXlN/muU1pCavxRa8vCOUnpxEKKLQqbvgBouUaNcW
    FolVMsLCaH2QtmXkfpou/PIbg+dOWcNPORap1iEgUJiprP1J1Q==
    ---- END SSH2 PUBLIC KEY ----

**Comment by fasterthanlime** [comment]
After some investigation:

  * Recent versions of puttygen show an openssh compatible version of your public key, ready to copy/paste somewhere:
![putty-public-key](https://cloud.githubusercontent.com/assets/7998310/13202967/772dde02-d8ab-11e5-9f44-f216f5f2886f.png)

  * The .ppk format has 2/3 internal variants, it seems the canonical way to go about it is to convert it to an OpenSSH private key using putty's own puttygen.

I feel like the best way to go about it is to simply document the process somewhere.

**Comment by fasterthanlime** [comment]
Hey we don't use SSH keys anymore! OAuth for the (relative) win.
