### ISSUE TITLE
linux64 download not working via wget

### ISSUE THREAD

**Issue by josefnpat** [itchio/butler#85]
I am not sure what is wrong, but I have followed the directions on:

https://itch.io/docs/butler/installing.html

This is ubuntu 12.04.05 LTS 64bit

![image](https://cloud.githubusercontent.com/assets/646162/19916760/439d20f4-a08b-11e6-9f49-6209e46c97e5.png)

**Comment by fasterthanlime** [comment]
Can you run the following commands?

```
sudo apt-cache show libc6
```

And

```
ldd ~/bin/butler
```

And

```
objdump -T ~/bin/butler | grep GLIBC
```

**Comment by josefnpat** [comment]
Sure!
http://pastebin.com/raw/Tv2PtxU4

**Comment by fasterthanlime** [comment]
Hmm any ideas why your `apt-cache show` only shows 32-bit libraries?

What does `uname -a` print? What about `lsb_release -a` ?

**Comment by josefnpat** [comment]
I'm not sure myself, I do find that odd:

```
seppi@penguinista:~$ uname -a
Linux penguinista 4.5.5-x86_64-linode69 #3 SMP Fri May 20 15:25:13 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
seppi@penguinista:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:        12.04
Codename:       precise
```

**Comment by fasterthanlime** [comment]
I know this is a pretty old thread but, have you given the windows-386 a shot?

Also, what's the output of `file $(which bash)` ?

**Comment by josefnpat** [comment]
Hey @fasterthanlime 

Not sure how you want me to give the windows 386 a shot without wine.

```
seppi@penguinista:~$ wget https://dl.itch.ovh/butler/windows-386/head/butler.exe--2016-12-29 03:37:15--  https://dl.itch.ovh/butler/windows-386/head/butler.exe
Resolving dl.itch.ovh (dl.itch.ovh)... 2400:cb00:2048:1::681b:868d, 2400:cb00:2048:1::681b:878d, 104.27.134.141, ...
Connecting to dl.itch.ovh (dl.itch.ovh)|2400:cb00:2048:1::681b:868d|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13471384 (13M) [application/x-msdos-program]
Saving to: `butler.exe'

100%[======================================>] 13,471,384  22.1M/s   in 0.6s    

2016-12-29 03:37:16 (22.1 MB/s) - `butler.exe' saved [13471384/13471384]

seppi@penguinista:~$ md5sum butler.exe 
0b36663aa62b5b875cf3e22a74b39b16  butler.exe
seppi@penguinista:~$ file $(which bash)
/bin/bash: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=0x86cce5c27536d3c3a065c8c4a81b616a2d974ba0, stripped
```

**Comment by josefnpat** [comment]
Now I'm confused ...


```
seppi@penguinista:~$ wget https://dl.itch.ovh/butler/linux-386/head/butler
--2016-12-31 04:44:32--  https://dl.itch.ovh/butler/linux-386/head/butler
Resolving dl.itch.ovh (dl.itch.ovh)... 2400:cb00:2048:1::681b:868d, 2400:cb00:2048:1::681b:878d, 104.27.134.141, ...
Connecting to dl.itch.ovh (dl.itch.ovh)|2400:cb00:2048:1::681b:868d|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14450960 (14M) [application/octet-stream]
Saving to: `butler'

100%[===================================================>] 14,450,960  18.4M/s   in 0.8s    

2016-12-31 04:44:33 (18.4 MB/s) - `butler' saved [14450960/14450960]

seppi@penguinista:~$ chmod a+x ./butler
seppi@penguinista:~$ ./butler 
usage: butler [<flags>] <command> [<args> ...]

Your happy little itch.io helper

Flags:
  -h, --help               Show context-sensitive help (also try --help-long and --help-man).
  -v, --verbose            Be very chatty about what's happening
      --assume-yes         Don't ask questions, just proceed (at your own risk!)
  -i, --identity="/home/seppi/.config/itch/butler_creds"  
                           Path to your itch.io API token
      --ignore=IGNORE ...  Glob patterns of files to ignore when diffing
  -V, --version            Show application version.

Commands:
  help [<command>...]
  login
  logout
  push [<flags>] <src> <target>
  fetch <target> <out>
  status [<flags>] <target>
  file <file>
  ls <file>
  which
  version
  upgrade [<flags>]
  update [<flags>]
  sign [<flags>] <dir> <signature>
  verify [<flags>] <signature> <dir>
  diff [<flags>] <old> <new> [<patch>]
  apply [<flags>] <patch> <old>
  heal <dir> <wounds> <spec>

seppi@penguinista:~$ uname -a
Linux penguinista 4.5.5-x86_64-linode69 #3 SMP Fri May 20 15:25:13 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
```

I obviously have a x86_64 machine ...

**Comment by fasterthanlime** [comment]
> Now I'm confused ...

So am I! but good news, you can run butler now :)

I've seen that happen (discrepancy between kernel/uname/system packages) in docker containers / chroots - I assume that's not your case?

**Comment by josefnpat** [comment]
Well, this is a linode VPS. What's the best way to check for this discrepancy?

**Comment by fasterthanlime** [comment]
(necroing this thread, hi!)

> Well, this is a linode VPS. What's the best way to check for this discrepancy?

I'm not actually sure what the best way is :panda_face: - but I'm assuming we can close this since you can run the 32-bit build there?

I'm sure this issue will come in handy in the future, if someone runs into this again!

**Comment by josefnpat** [comment]
@fasterthanlime yeah, totall!

**Comment by Hello71** [comment]
In 2016, Linode loaded the kernel from the host, not the guest. This was because Linode used Xen PV which can't run the 16-bit BIOS bootloader in the guest, and the technology for reading the GRUB configuration in the host from the guest image wasn't fully developed. In this case, a 64-bit kernel was selected in the Linode settings, and a 32-bit Ubuntu was installed in the guest. This works fine because multilib is enabled in the kernel, so 32-bit binaries run normally.

ldd says butler is "not a dynamic executable", but it's lying; butler is a dynamic executable, and it needs 64-bit glibc to be installed. The reason ldd says that is because it runs glibc to parse the executable, and glibc says "i dunno what this is", and ldd translates that to "not a dynamic executable". I believe modern versions of glibc handle this case better. Anyways, if butler really was a static executable, then it would run perfectly fine, because a 64-bit kernel is in use, as shown by uname, but it's not; it needs 64-bit glibc, and none is installed, so the confusing message "No such file or directory" is shown. The correct solution is to install 64-bit Ubuntu (which I think can actually be done on top of the existing system with apt?), or if that's not possible, use 32-bit butler.
