### ISSUE TITLE
Could not create resumable upload session (got HTTP 403)

### ISSUE THREAD

**Issue by carlestyle** [itchio/butler#89]
Hi all, this is my first time trying butler to upload my builds automatically to my itch.io page. I've followed all the steps in [this guide](https://itch.io/docs/butler/pushing.html) but no matter what I do I get the following error:

```
Started resumable upload session
*errors.errorString could not create resumable upload session (got HTTP 403)
C:/Go/src/runtime/asm_386.s:1612 (0x479f11)
```

Any idea what this means and also how can I fix this issue? I would really like to automate builds. Butler looks promising but I'm stuck at the very beginning.

**Comment by fasterthanlime** [comment]
Hey, 

This issue has been popping up for non-US users ever since our last server migration, we're looking into it and will keep you updated once we find out what's going on!

/cc @leafo

**Comment by leafo** [comment]
I think it's happening to everyone. I didn't diagnose it correctly because pushing an initial build fails in a different way. I'm investigating now.

**Comment by leafo** [comment]
This should be fixed now, I'm able to push builds. @carlestyle could I have you test?

**Comment by carlestyle** [comment]
I just tried it. Thanks @leafo and @fasterthanlime it works perfectly now 👍
